# EDA temporario (testing)

In [1]:
import os
import pandas as pd

In [2]:
os.chdir("..")
os.getcwd()

'/home/troonies/repos/itba-aws-mle'

## Data

Detailed info on **flight arrivals and delays for U.S. airports**, categorized by carriers.

It includes metrics such as the number of arriving flights, delays over 15 minutes, cancellation and diversion counts, and the breakdown of delays attributed to carriers, weather, NAS (National Airspace System), security, and late aircraft arrivals.

In [3]:
cols_descriptions = {
    "year":         "Year of the data",
    "month":        "Month of the data",
    "carrier":      "Carrier code",
    "carrier_name": "Carrier name",
    "airport":      "Airport code",
    "airport_name": "Airport name",
    "arr_flights":      "Number of arriving flights",
    "arr_del15":        "Number of flights delayed by 15 minutes or more",
    "carrier_ct":       "Carrier count (delay due to the carrier)",
    "weather_ct":       "Weather count (delay due to weather)",
    "nas_ct":           "NAS (National Airspace System) count (delay due to the NAS)",
    "security_ct":      "Security count (delay due to security)",
    "late_aircraft_ct": "Late aircraft count (delay due to late aircraft arrival)",
    "arr_cancelled":    "Number of flights canceled",
    "arr_diverted":     "Number of flights diverted",
    "arr_delay":           "Total arrival delay",
    "carrier_delay":       "Delay attributed to the carrier",
    "weather_delay":       "Delay attributed to weather",
    "nas_delay":           "Delay attributed to the NAS",
    "security_delay":      "Delay attributed to security",
    "late_aircraft_delay": "Delay attributed to late aircraft arrival",
}

In [4]:
cols_types = {
    "int": [
        "year",
        "month",
        "arr_flights",
        "arr_del15",
        "arr_cancelled",
        "arr_diverted",
        "arr_delay",
        "carrier_delay",
        "weather_delay",
        "nas_delay",
        "security_delay",
        "late_aircraft_delay",
    ],
    "float": [
        "carrier_ct",
        "weather_ct",
        "nas_ct",
        "security_ct",
        "late_aircraft_ct",
    ],
    "cat": [
        "carrier",
        "carrier_name",
        "airport",
        "airport_name",
    ],
}

Use training and validation splits only for the EDA.

In [5]:
df = pd.read_csv("data/train_val.csv")
df

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2013,10,B6,JetBlue Airways,SLC,"Salt Lake City, UT: Salt Lake City International",93.0,12.0,4.04,0.00,...,0.73,5.23,0.0,0.0,649.0,208.0,0.0,54.0,37.0,350.0
1,2015,4,UA,United Air Lines Inc.,SNA,"Santa Ana, CA: John Wayne Airport-Orange County",449.0,81.0,34.33,2.23,...,0.00,28.87,2.0,5.0,3698.0,1263.0,75.0,580.0,0.0,1780.0
2,2015,10,DL,Delta Air Lines Inc.,HSV,"Huntsville, AL: Huntsville International-Carl ...",172.0,6.0,1.78,0.00,...,0.00,3.00,0.0,0.0,214.0,67.0,0.0,22.0,0.0,125.0
3,2016,3,EV,ExpressJet Airlines Inc.,CRW,"Charleston/Dunbar, WV: Yeager",174.0,29.0,14.62,0.00,...,0.00,6.13,2.0,3.0,1581.0,929.0,0.0,336.0,0.0,316.0
4,2019,10,F9,Frontier Airlines Inc.,GSP,"Greer, SC: Greenville-Spartanburg International",29.0,2.0,1.12,0.00,...,0.00,0.88,1.0,0.0,105.0,55.0,0.0,0.0,0.0,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154494,2016,10,OO,SkyWest Airlines Inc.,EWR,"Newark, NJ: Newark Liberty International",36.0,5.0,0.00,0.82,...,0.00,0.00,0.0,0.0,146.0,0.0,42.0,104.0,0.0,0.0
154495,2015,8,DL,Delta Air Lines Inc.,GSO,"Greensboro/High Point, NC: Piedmont Triad Inte...",180.0,28.0,6.93,2.98,...,0.00,12.86,0.0,0.0,2183.0,374.0,802.0,210.0,0.0,797.0
154496,2015,10,OO,SkyWest Airlines Inc.,FLG,"Flagstaff, AZ: Flagstaff Pulliam",158.0,37.0,9.32,0.00,...,0.00,11.65,1.0,2.0,1423.0,544.0,0.0,397.0,0.0,482.0
154497,2023,1,AA,American Airlines Inc.,BNA,"Nashville, TN: Nashville International",622.0,142.0,45.98,2.90,...,1.19,50.32,9.0,1.0,8722.0,2549.0,456.0,1788.0,38.0,3891.0
154498,2016,2,WN,Southwest Airlines Co.,MAF,"Midland/Odessa, TX: Midland International Air ...",243.0,23.0,9.96,0.00,...,0.00,12.57,1.0,0.0,899.0,398.0,0.0,21.0,0.0,480.0

## Transformations

In [6]:
# 1. Eliminate general null cols (a certain important col? a minimum amount of nulls like 3?)
# ?. (Ignoring nulls) Round outliers to the min and max allowable (ICR? whiskers?)
# ?. Fill nulls with mean, and round it to the nearest integer if col is int-based
# ?. Standardize: Mean to 0 and std to 1

In [7]:
df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2013,10,B6,JetBlue Airways,SLC,"Salt Lake City, UT: Salt Lake City International",93.0,12.0,4.04,0.00,...,0.73,5.23,0.0,0.0,649.0,208.0,0.0,54.0,37.0,350.0
1,2015,4,UA,United Air Lines Inc.,SNA,"Santa Ana, CA: John Wayne Airport-Orange County",449.0,81.0,34.33,2.23,...,0.00,28.87,2.0,5.0,3698.0,1263.0,75.0,580.0,0.0,1780.0
2,2015,10,DL,Delta Air Lines Inc.,HSV,"Huntsville, AL: Huntsville International-Carl ...",172.0,6.0,1.78,0.00,...,0.00,3.00,0.0,0.0,214.0,67.0,0.0,22.0,0.0,125.0
3,2016,3,EV,ExpressJet Airlines Inc.,CRW,"Charleston/Dunbar, WV: Yeager",174.0,29.0,14.62,0.00,...,0.00,6.13,2.0,3.0,1581.0,929.0,0.0,336.0,0.0,316.0
4,2019,10,F9,Frontier Airlines Inc.,GSP,"Greer, SC: Greenville-Spartanburg International",29.0,2.0,1.12,0.00,...,0.00,0.88,1.0,0.0,105.0,55.0,0.0,0.0,0.0,50.0

### Functions

In [8]:
def cast_everything_to_float(df: pd.DataFrame) -> pd.DataFrame:
    """Cast all numeric columns to float."""
    df = df.astype({c: float for c in cols_types["int"]})
    df = df.astype({c: float for c in cols_types["float"]})
    return df

def drop_null_rows(df: pd.DataFrame) -> pd.DataFrame:
    """Drop rows that have too many nulls."""
    return df[df["arr_flights"].notnull()]

def standardize_cols(df: pd.DataFrame, df_desc: pd.DataFrame) -> pd.DataFrame:
    """Standardize columns."""
    for c in (cols_types["int"] + cols_types["float"]):
        df[c] = df[c] - df_desc.at["mean", c]
        df[c] = df[c] / df_desc.at["std", c]
    return df

def limit_outliers(df: pd.DataFrame, df_whiskers: pd.DataFrame) -> pd.DataFrame:
    """Limit outlier values by rounding them to the corresponding boxplot whisker value."""
    for c in (cols_types["int"] + cols_types["float"]):
        low_w = df_whiskers.at[c, "lower_whisker"]
        high_w = df_whiskers.at[c, "upper_whisker"]

        df[f"{c}_lower_out"] = df[c] < low_w
        df[f"{c}_high_out"] = high_w < df[c]

        if df[f"{c}_lower_out"].any():
            df[c] = df[[c, f"{c}_lower_out"]].apply(lambda row: low_w if row[f"{c}_lower_out"] else row[c], axis=1)
        del df[f"{c}_lower_out"], low_w

        if df[f"{c}_high_out"].any():
            df[c] = df[[c, f"{c}_high_out"]].apply(lambda row: high_w if row[f"{c}_high_out"] else row[c], axis=1)
        del df[f"{c}_high_out"], high_w

    return df

### Apply transformations

In [9]:
df_new = df.copy()

In [10]:
df_new = df_new.drop(["carrier_name", "airport_name"], axis=1)
df_new = cast_everything_to_float(df_new)
df_new = drop_null_rows(df_new)

In [11]:
df_desc_orig = df_new.describe()
df_desc_orig

,year,month,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
count,154285.000000,154285.000000,154285.000000,154105.000000,154285.000000,154285.000000,154285.000000,154285.000000,154285.000000,154285.000000,154285.000000,154285.000000,154285.000000,154285.000000,154285.000000,154285.000000,154285.000000
mean,2018.550702,6.488693,361.265301,66.196957,20.736448,2.245162,19.299237,0.156049,23.682863,7.525832,0.860103,4224.400791,1432.920783,222.062145,916.194031,7.340364,1645.878783
std,2.889562,3.443435,990.605319,179.016415,50.197224,7.291439,61.375138,0.717411,72.257752,44.136378,3.731641,12599.400773,4216.431568,817.515916,3407.849658,41.771790,5217.585794
min,2013.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2016.000000,3.000000,50.000000,6.000000,2.160000,0.000000,1.000000,0.000000,1.230000,0.000000,0.000000,334.000000,110.000000,0.000000,34.000000,0.000000,65.000000
50%,2019.000000,7.000000,100.000000,17.000000,6.400000,0.390000,3.910000,0.000000,5.000000,1.000000,0.000000,1016.000000,374.000000,18.000000,146.000000,0.000000,320.000000
75%,2021.000000,9.000000,249.000000,47.000000,17.250000,1.860000,11.700000,0.000000,15.250000,4.000000,1.000000,2877.000000,1109.000000,146.000000,477.000000,0.000000,1068.000000
max,2023.000000,12.000000,21977.000000,4176.000000,1293.910000,266.420000,1884.420000,58.690000,2069.070000,4951.000000,197.000000,438783.000000,196944.000000,31960.000000,112018.000000,3760.000000,227959.000000

In [12]:
df_new = standardize_cols(df_new, df_desc=df_desc_orig)

In [13]:
df_new.head()

,year,month,carrier,airport,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,-1.920949,1.019710,B6,SLC,-0.270809,-0.302749,-0.332617,-0.307917,-0.281861,0.800031,-0.255376,-0.170513,-0.230489,-0.283775,-0.290511,-0.271630,-0.253002,0.710040,-0.248368
1,-1.228803,-0.722736,UA,SNA,0.088567,0.082691,0.270803,-0.002079,-0.060761,-0.217517,0.071787,-0.125199,1.109404,-0.041780,-0.040300,-0.179889,-0.098653,-0.175725,0.025706
2,-1.228803,1.019710,DL,HSV,-0.191060,-0.336265,-0.377639,-0.307917,-0.294569,-0.217517,-0.286237,-0.170513,-0.230489,-0.318301,-0.323952,-0.271630,-0.262392,-0.175725,-0.291491
3,-0.882730,-1.013143,EV,CRW,-0.189041,-0.207785,-0.121848,-0.307917,-0.179865,-0.217517,-0.242920,-0.125199,0.573447,-0.209804,-0.119514,-0.271630,-0.170252,-0.175725,-0.254884
4,0.155490,1.019710,F9,GSP,-0.335416,-0.358609,-0.390788,-0.307917,-0.314447,-0.217517,-0.315577,-0.147856,-0.230489,-0.326952,-0.326798,-0.271630,-0.268848,-0.175725,-0.305865

In [14]:
df_desc = df_new.describe()
df_desc.loc["iqr", :] = df_desc.loc["75%", :] -  df_desc.loc["25%", :]
df_desc.loc["iqr_x_1_5", :] = 1.5 * df_desc.loc["iqr", :]
df_desc.loc["lower_whisker", :] = df_desc.loc["25%", :] - df_desc.loc["iqr_x_1_5", :]
df_desc.loc["upper_whisker", :] = df_desc.loc["75%", :] + df_desc.loc["iqr_x_1_5", :]
df_desc

,year,month,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
count,1.542850e+05,1.542850e+05,1.542850e+05,1.541050e+05,1.542850e+05,1.542850e+05,1.542850e+05,1.542850e+05,1.542850e+05,1.542850e+05,1.542850e+05,1.542850e+05,1.542850e+05,1.542850e+05,1.542850e+05,1.542850e+05,1.542850e+05
mean,1.687618e-14,8.423260e-17,1.487541e-17,-1.498500e-17,-2.170290e-17,5.441269e-17,-3.840896e-17,1.547411e-17,-2.526057e-17,8.289704e-18,7.161383e-18,-3.635956e-17,-2.782807e-17,-2.394803e-18,-1.639519e-17,4.973822e-18,1.908935e-17
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-1.920949e+00,-1.593958e+00,-3.636820e-01,-3.697815e-01,-4.130995e-01,-3.079175e-01,-3.144472e-01,-2.175174e-01,-3.277553e-01,-1.705131e-01,-2.304893e-01,-3.352858e-01,-3.398421e-01,-2.716304e-01,-2.688481e-01,-1.757254e-01,-3.154483e-01
25%,-8.827296e-01,-1.013143e+00,-3.142173e-01,-3.362650e-01,-3.700692e-01,-3.079175e-01,-2.981539e-01,-2.175174e-01,-3.107329e-01,-1.705131e-01,-2.304893e-01,-3.087767e-01,-3.137536e-01,-2.716304e-01,-2.588712e-01,-1.757254e-01,-3.029905e-01
50%,1.554901e-01,1.484875e-01,-2.637431e-01,-2.748181e-01,-2.856024e-01,-2.544301e-01,-2.507406e-01,-2.175174e-01,-2.585586e-01,-1.478561e-01,-2.304893e-01,-2.546471e-01,-2.511415e-01,-2.496124e-01,-2.260059e-01,-1.757254e-01,-2.541173e-01
75%,8.476366e-01,7.293028e-01,-1.133300e-01,-1.072357e-01,-6.945500e-02,-5.282381e-02,-1.238162e-01,-2.175174e-01,-1.167053e-01,-7.988494e-02,3.748939e-02,-1.069417e-01,-7.682344e-02,-9.304057e-02,-1.288772e-01,-1.757254e-01,-1.107560e-01
max,1.539783e+00,1.600526e+00,2.182073e+01,2.295769e+01,2.536343e+01,3.623082e+01,3.038886e+01,8.159055e+01,2.830682e+01,1.120045e+02,5.256131e+01,3.449042e+01,4.636885e+01,3.882241e+01,3.260173e+01,8.983718e+01,4.337506e+01
iqr,1.730366e+00,1.742446e+00,2.008873e-01,2.290293e-01,3.006142e-01,2.550937e-01,1.743377e-01,0.000000e+00,1.940276e-01,9.062819e-02,2.679787e-01,2.018350e-01,2.369302e-01,1.785898e-01,1.299940e-01,0.000000e+00,1.922345e-01
iqr_x_1_5,2.595549e+00,2.613669e+00,3.013309e-01,3.435439e-01,4.509214e-01,3.826405e-01,2.615065e-01,0.000000e+00,2.910414e-01,1.359423e-01,4.019680e-01,3.027525e-01,3.553953e-01,2.678847e-01,1.949910e-01,0.000000e+00,2.883518e-01
lower_whisker,-3.478279e+00,-3.626812e+00,-6.155482e-01,-6.798089e-01,-8.209906e-01,-6.905580e-01,-5.596605e-01,-2.175174e-01,-6.017744e-01,-3.064554e-01,-6.324572e-01,-6.115291e-01,-6.691490e-01,-5.395151e-01,-4.538622e-01,-1.757254e-01,-5.913422e-01
upper_whisker,3.443186e+00,3.342972e+00,1.880009e-01,2.363082e-01,3.814664e-01,3.298167e-01,1.376903e-01,-2.175174e-01,1.743361e-01,5.605734e-02,4.394574e-01,1.958108e-01,2.785719e-01,1.748441e-01,6.611382e-02,-1.757254e-01,1.775958e-01

In [15]:
df_whiskers = df_desc.loc[["lower_whisker", "upper_whisker"],:].T
df_whiskers

                     lower_whisker  upper_whisker
year                     -3.478279       3.443186
month                    -3.626812       3.342972
arr_flights              -0.615548       0.188001
arr_del15                -0.679809       0.236308
carrier_ct               -0.820991       0.381466
weather_ct               -0.690558       0.329817
nas_ct                   -0.559660       0.137690
security_ct              -0.217517      -0.217517
late_aircraft_ct         -0.601774       0.174336
arr_cancelled            -0.306455       0.056057
arr_diverted             -0.632457       0.439457
arr_delay                -0.611529       0.195811
carrier_delay            -0.669149       0.278572
weather_delay            -0.539515       0.174844
nas_delay                -0.453862       0.066114
security_delay           -0.175725      -0.175725
late_aircraft_delay      -0.591342       0.177596

In [16]:
df_new = limit_outliers(df_new, df_whiskers=df_whiskers)

In [17]:
df_new

,year,month,carrier,airport,arr_flights,arr_del15,carrier_ct,weather_ct,nas_ct,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,-1.920949,1.019710,B6,SLC,-0.270809,-0.302749,-0.332617,-0.307917,-0.281861,-0.217517,-0.255376,-0.170513,-0.230489,-0.283775,-0.290511,-0.271630,-0.253002,-0.175725,-0.248368
1,-1.228803,-0.722736,UA,SNA,0.088567,0.082691,0.270803,-0.002079,-0.060761,-0.217517,0.071787,-0.125199,0.439457,-0.041780,-0.040300,-0.179889,-0.098653,-0.175725,0.025706
2,-1.228803,1.019710,DL,HSV,-0.191060,-0.336265,-0.377639,-0.307917,-0.294569,-0.217517,-0.286237,-0.170513,-0.230489,-0.318301,-0.323952,-0.271630,-0.262392,-0.175725,-0.291491
3,-0.882730,-1.013143,EV,CRW,-0.189041,-0.207785,-0.121848,-0.307917,-0.179865,-0.217517,-0.242920,-0.125199,0.439457,-0.209804,-0.119514,-0.271630,-0.170252,-0.175725,-0.254884
4,0.155490,1.019710,F9,GSP,-0.335416,-0.358609,-0.390788,-0.307917,-0.314447,-0.217517,-0.315577,-0.147856,-0.230489,-0.326952,-0.326798,-0.271630,-0.268848,-0.175725,-0.305865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154494,-0.882730,1.019710,OO,EWR,-0.328350,-0.341851,-0.413100,-0.195457,-0.246341,-0.217517,-0.327755,-0.170513,-0.230489,-0.323698,-0.339842,-0.220255,-0.238330,-0.175725,-0.315448
154495,-1.228803,0.438895,DL,GSO,-0.182984,-0.213371,-0.275044,0.100781,-0.229233,-0.217517,-0.149781,-0.170513,-0.230489,-0.162024,-0.251141,0.174844,-0.207226,-0.175725,-0.162696
154496,-1.228803,1.019710,OO,FLG,-0.205193,-0.163097,-0.227432,-0.307917,-0.053104,-0.217517,-0.166527,-0.147856,0.305468,-0.222344,-0.210823,-0.271630,-0.152352,-0.175725,-0.223068
154497,1.539783,-1.593958,AA,BNA,0.188001,0.236308,0.381466,0.089809,0.137690,-0.217517,0.174336,0.033400,0.037489,0.195811,0.264698,0.174844,0.066114,-0.175725,0.177596
154498,-0.882730,-1.303551,WN,MAF,-0.119387,-0.241302,-0.214682,-0.307917,-0.306789,-0.217517,-0.153795,-0.147856,-0.230489,-0.263933,-0.245449,-0.271630,-0.262686,-0.175725,-0.223452

We should do the standardization again with the original data and with mean and std calculated anew, but we'll skip this step

In [18]:
# Fill nulls
df_new["arr_del15"] = df_new["arr_del15"].fillna(df_desc.at["mean", "arr_del15"])
df_new.isnull().sum()

year                   0
month                  0
carrier                0
airport                0
arr_flights            0
arr_del15              0
carrier_ct             0
weather_ct             0
nas_ct                 0
security_ct            0
late_aircraft_ct       0
arr_cancelled          0
arr_diverted           0
arr_delay              0
carrier_delay          0
weather_delay          0
nas_delay              0
security_delay         0
late_aircraft_delay    0
dtype: int64